import { Event } from '../types';

export const STATIC_EVENTS: Event[] = [
  {
    "id": "scraped-1",
    "title": "Muxabbat qosıǵı",
    "description": "Muxabbat qosıǵı - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2026-02/1771661420_photo_2026-02-21_10-39-55.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": true
  },
  {
    "id": "scraped-2",
    "title": "\"VAVILONNÍŃ EŃ BAY ADAMÍ\"",
    "description": "\"VAVILONNÍŃ EŃ BAY ADAMÍ\" - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2026-02/1771652154_photo_2026-02-21_10-32-05.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": true
  },
  {
    "id": "scraped-3",
    "title": "\"Súymegenge súykenbe\"",
    "description": "\"Súymegenge súykenbe\" - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2026-02/1771651766_photo_2026-02-21_10-26-55.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": true
  },
  {
    "id": "scraped-4",
    "title": "Qanlı toy afisha",
    "description": "Qanlı toy afisha - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2025-09/1757046096_2.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": true
  },
  {
    "id": "scraped-5",
    "title": "NAZLÍMXAN SULÍW",
    "description": "NAZLÍMXAN SULÍW - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2025-09/1757045836_1.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-6",
    "title": "DARAXTLARNING MUNGLI QO‘SHIG‘I",
    "description": "DARAXTLARNING MUNGLI QO‘SHIG‘I - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2026-02/1771651410_photo_2026-02-21_10-22-28.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-7",
    "title": "BIR QÁDEM",
    "description": "BIR QÁDEM - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2025-03/1742366287_1.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-8",
    "title": "GÓZZALLARǴA SAWǴA",
    "description": "GÓZZALLARǴA SAWǴA - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2025-03/1742366620_11.jpg",
    "category": "concert",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-9",
    "title": "AFISHA  TERBENBES JÚREKLER",
    "description": "AFISHA  TERBENBES JÚREKLER - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2025-02/1740559957_8.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-10",
    "title": "Qaraqalpaq qızı",
    "description": "Qaraqalpaq qızı - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2025-02/1739340762_1.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-11",
    "title": "Афиша \"ЖАР\"",
    "description": "Афиша \"ЖАР\" - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2024-11/1731990693_350.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-12",
    "title": "\"АРАЛЫМ МЕНИҢ\" моноопер",
    "description": "\"АРАЛЫМ МЕНИҢ\" моноопер - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2024-08/1723180307_15.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-13",
    "title": "\"АРАЛЫМ МЕНИҢ\" моноопера",
    "description": "\"АРАЛЫМ МЕНИҢ\" моноопера - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2024-08/1723180130_15.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-14",
    "title": "\"ӘЖИНИЯЗ\" операсы",
    "description": "\"ӘЖИНИЯЗ\" операсы - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2024-06/1718282234_1.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-15",
    "title": "«Гоззалларға саўға»",
    "description": "«Гоззалларға саўға» - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2024-03/1709527088_1.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-16",
    "title": "\"МЕН, КЕМПИР АПАМ, ИЛИКО ҲӘМ ИЛЛАРИОН\"",
    "description": "\"МЕН, КЕМПИР АПАМ, ИЛИКО ҲӘМ ИЛЛАРИОН\" - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2023-12/1703248067_18.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-17",
    "title": "\"Едиге-Тоқтамыс-Амир Темур\" тарийхый операсы",
    "description": "\"Едиге-Тоқтамыс-Амир Темур\" тарийхый операсы - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2023-12/1702961037_15.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-18",
    "title": "\"Абу Райхан Беруний\" тарийхый драма спектакли",
    "description": "\"Абу Райхан Беруний\" тарийхый драма спектакли - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2023-12/1702960741_12.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-20",
    "title": "Ж.Б.Мольердиң “Гүңелек қыз ҳәм тәӯип”  комедиясы",
    "description": "Ж.Б.Мольердиң “Гүңелек қыз ҳәм тәӯип”  комедиясы - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2023-06/1686369555_1.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-21",
    "title": "Сая Қасымбектиң «ЛИФТ» спектакли",
    "description": "Сая Қасымбектиң «ЛИФТ» спектакли - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2023-06/1686026947_lift.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-22",
    "title": "У.Шекспирдиң «Гамлет» трагедиясы",
    "description": "У.Шекспирдиң «Гамлет» трагедиясы - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2023-06/1685945674_1.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-23",
    "title": "А.Қодирийдиң “Өткен күнлер” драмасы",
    "description": "А.Қодирийдиң “Өткен күнлер” драмасы - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2023-02/1676614322_11.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-24",
    "title": "П.И.Чайковскийдиң “Щелкунчик” балети.",
    "description": "П.И.Чайковскийдиң “Щелкунчик” балети. - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2023-02/thumbs/1676606766_1641625293_photo_2022-01-08_11-58-57.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-25",
    "title": "«Халық ушын» операсы.",
    "description": "«Халық ушын» операсы. - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2022-09/1663569239_photo_2022-09-13_11-19-45.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-26",
    "title": "Ески афишалар",
    "description": "Ески афишалар - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2022-03/1648537228_8.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-27",
    "title": "1926-2022 жылларда сахналастырылған спектакльлер",
    "description": "1926-2022 жылларда сахналастырылған спектакльлер - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2021-12/1639723671_teatr.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-28",
    "title": "«Қырық қыз» драмасы",
    "description": "«Қырық қыз» драмасы - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2021-11/1637993200_photo_2021-11-27_10-58-38.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-29",
    "title": "«Ғәрип ашық»  музыкалы драма",
    "description": "«Ғәрип ашық»  музыкалы драма - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2021-11/1636126267_afisha-garib-ashyk.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-30",
    "title": "ҰШ БОЙДАҚ",
    "description": "ҰШ БОЙДАҚ - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2021-11/1636025884_ush-bojdak.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-31",
    "title": "АЖИНИЯЗ операсы",
    "description": "АЖИНИЯЗ операсы - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2021-10/1633083907_100.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-32",
    "title": "К.Рахмановтың “Ынжықтың муҳаббаты” комедиясы",
    "description": "К.Рахмановтың “Ынжықтың муҳаббаты” комедиясы - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2021-11/1636045135_34.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-33",
    "title": "«Гөззалларға саўға» театрластырылған байрам тамашасы",
    "description": "«Гөззалларға саўға» театрластырылған байрам тамашасы - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2021-03/1615293460_afisha.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-34",
    "title": "АНА драмасы",
    "description": "АНА драмасы - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2021-02/1614526793_22.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-35",
    "title": "Спектакль \"Ийман\", \"Тирсеклер\"",
    "description": "Спектакль \"Ийман\", \"Тирсеклер\" - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2020-11/1606472701_5.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-36",
    "title": "Бердак",
    "description": "Бердак - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2020-10/1602421049_27.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-37",
    "title": "Гулайым операсы",
    "description": "Гулайым операсы - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2020-10/1602421577_24.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-38",
    "title": "АЛПАМЫС",
    "description": "АЛПАМЫС - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2020-10/1603711757_alpamys.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-39",
    "title": "ИМАН",
    "description": "ИМАН - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2020-10/1603628315_photo_2019-12-06_17-22-56.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  },
  {
    "id": "scraped-40",
    "title": "ЕДИГЕ",
    "description": "ЕДИГЕ - Berdaq atındaǵı teatr afishası",
    "bannerImage": "https://berdax-teatr.uz/uploads/posts/2020-10/thumbs/1603557568_2.jpg",
    "category": "theater",
    "date": "2026-06-15",
    "time": "18:00",
    "location": "Berdaq atındaǵı teatr",
    "price": "50,000 UZS",
    "isTopEvent": false
  }
];
